### ISSUE TITLE
use your constant for the y

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/GameProgramTTT#12]
https://github.com/Selemabala/GameProgramTTT/blob/1381db0ad3edf5e97c1657e0860db603711eede3/GameProgramTTT/UI.cs#L24

Even though it's a message, the constant should be used. And this is because if you decide to change the accepter answer, you can do it easily by changing a constant.

**Comment by Selemabala** [comment]
Instead of using y in a message, the constant has been used.
