### ISSUE TITLE
Why don't you convert your input to lower case?

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/GameProgramTTT#13]
https://github.com/Selemabala/GameProgramTTT/blob/1381db0ad3edf5e97c1657e0860db603711eede3/GameProgramTTT/Program.cs#L13-L15

By changing to lower case you will have to check only one condition and not 2. 

this can be applied to GetGamePlayer() also.

**Comment by Selemabala** [comment]
I used the ToUpper and ToLower method to convert the user input so that I dont do the same thing twice.
