### ISSUE TITLE
This checks also for vertical wins

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/GameProgramTTT#16]
https://github.com/Selemabala/GameProgramTTT/blob/1381db0ad3edf5e97c1657e0860db603711eede3/GameProgramTTT/Logic.cs#L45

This method also checks for vertical wins but only the horizontals are on the name

**Comment by Selemabala** [comment]
The name of the Method was reflecting only one thing which it does, now it reflects everything is does which is checking for Vertical and Horizontal Wins
