### ISSUE TITLE
Method names are bad

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/GameProgramTTT#2]
https://github.com/Selemabala/GameProgramTTT/blob/e7cf689c400020c98223a6082ff95ef510551e5e/GameProgramTTT/Program.cs#L13-L15

In general your method names are bad. Naming a method should follow a verb-noun conversion. This helps with explaining the action that this method takes. 

For all of those methods, there's no verb at all. You should rename all those methods better and also check all your methods that may have the same problem.

**Comment by Selemabala** [comment]
Method names have been modified.

WelcomeMessage - ShowWelcomeMessage

UserInput - GetUserInput

Gametime - DisplayGametime

WelcomeMessage.- ShowWelcomeMessage

NoWinnerResults -  ShowTieResults

GameLastStatement - DisplayLastThanksStatement

GameStarter - GetGameStarter

UserRowAndColumnInput - HumanPlaying

AiMove - AiPlaying


In Logic

WelcomeWord - ShowWelcomeWord

 UserAnswer - GetUserAnswer

GridIsFul - DisplayGridIsFull
