### ISSUE TITLE
Create a method out of this

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/GameProgramTTT#20]
https://github.com/Selemabala/GameProgramTTT/blob/f9bdbe8fead3957a27073c864dbf87f57c6e67ef/GameProgramTTT/Program.cs#L34-L41

your program only cares about the nextPlayer variable. You can hide the rest of the logic in a method.

**Comment by Selemabala** [comment]
After modifying this one I see the choice statement coming twice, I asked myself why? Then I tried looking it by debugging mode I came with some thoughts,  is it because I have created a variable which takes the value of the method created? What is the good idea to avoid this problem.
