### ISSUE TITLE
Is that if cased needed?

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/GameProgramTTT#4]
https://github.com/Selemabala/GameProgramTTT/blob/e7cf689c400020c98223a6082ff95ef510551e5e/GameProgramTTT/Program.cs#L47-L56

Your GameStarter() method (terrible name) returns back a boolean value which essentially means true-> AI and false -> Human. 

Is there any particular reason to have an if case to recheck that? 

Why don't you make a method that will return what you need immediately? If you don't use the bool and you need a string make your GameStarter() method return a string immediately. 

Also, we have talked about it in the past
when checking a boolean value in an if case you don't need to check if with == operator.

**Comment by Selemabala** [comment]
The variable name has been changed from GameStarter to GetGamePlayer. Also the the code has been modified from rechecking it to using the output straight.
