### ISSUE TITLE
This method should be broken down into more methods

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/GameProgramTTT#5]
https://github.com/Selemabala/GameProgramTTT/blob/e7cf689c400020c98223a6082ff95ef510551e5e/GameProgramTTT/UI.cs#L111

You can create separate methods to check separate conditions the same way as you have done for the slot machine. A method for verticals another for horizontals and another for diagonals. 

Important thing is to identify which methods can be Logical and which can be UI.

**Comment by Selemabala** [comment]
The method has been separated and two of them are now running. RevealHolizontalWins and RevealHolizontalWins
