### ISSUE TITLE
What is this method?

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/GameProgramTTT#6]
https://github.com/Selemabala/GameProgramTTT/blob/565f1d4d6ce3a9b074de09fdcce3c3e81a3074ed/GameProgramTTT/Logic.cs#L10-L14

It has a name that refers to showing a welcome message but it just returns a string. There's a variable named "john". That's not a name for a variable of course. And it exists in logic. 

Why do you have this method?

**Comment by Selemabala** [comment]
Method has been changed and moved to UI as just a statement and not a method.
