### ISSUE TITLE
This block can be a method

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/GameProgramTTT#8]
https://github.com/Selemabala/GameProgramTTT/blob/565f1d4d6ce3a9b074de09fdcce3c3e81a3074ed/GameProgramTTT/Program.cs#L15-L26

So you are getting the user's input and then return back the char on the program to have an if/else case to decide if the game is going to be played or not. 

And then you have another if/else in your program that checks the result. 

The greater the number of if/else cases the greater the complexity of a program. You can merge the first if/else (which decides if play will be true/false) into the GetuserInput or you can create another method to hide the if/else and return back a bool to be assigned to play

**Comment by Selemabala** [comment]
The codes have been merged. I now see clearly it was useless and stupid to have more codes doing almost the same thing
