### ISSUE TITLE
Avoid using Exit method

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/GameProgramTTT#9]
https://github.com/Selemabala/GameProgramTTT/blob/565f1d4d6ce3a9b074de09fdcce3c3e81a3074ed/GameProgramTTT/Program.cs#L28-L32

Environment.Exit(0); stops the application immediately without being able to execute some clean ups that the compiler does. It's better if you make the execution reach the end of the program if you want to stop it. In general avoid using Environment.Exit(0);

**Comment by Selemabala** [comment]
The code has been replaced by a return code. I tried to find ways to end the application without using Environment.Exit(0); and I found I can use the code return. I hoped to use break and I came to learn that break is used only in loops. I got knowledge about the return code here https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/jump-statements#the-return-statement
